name: Android Build

# https://docs.github.com/cn/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

on:
  watch:
    types: [started]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: clear [18PlusList.txt]
        run: |
          echo "">$GITHUB_WORKSPACE/app/src/main/assets/18PlusList.txt

      - name: Decrypt large secret
        run: bash ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.ANDROID_TEST }}

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name : upload apk
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: legado
          path: ./app/build/outputs/apk/app/release/
